# Notes
## Target
1. Revenue true / false
## Cleaning
1. No missing values in dataset.
0. Duplicates present - likely errors due to repeated values across specific columns

In [66]:
import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

# Data Exploration

In [67]:
# Importing dataset
dataset = pd.read_csv('dataset/online_shoppers_intention.csv')
dataset

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False

In [68]:
dataset.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [69]:
dataset.shape

(12330, 18)

In [70]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  str
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  str
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), str(2)
memory usage: 1.5 MB

In [71]:
dataset.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [72]:
# No missing values in the dataset
dataset.isna().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [73]:
# Duplicates may be present
dataset.duplicated().sum()

np.int64(125)

In [74]:
# Examine duplicates.
dataset[dataset.duplicated(keep=False)].head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
85,0,0.0,0,0.0,1,0.0,0.2,0.2,0.0,0.0,Feb,1,1,1,3,Returning_Visitor,False,False
132,0,0.0,0,0.0,1,0.0,0.2,0.2,0.0,0.0,Feb,3,2,3,3,Returning_Visitor,False,False
158,0,0.0,0,0.0,1,0.0,0.2,0.2,0.0,0.0,Feb,1,1,1,3,Returning_Visitor,False,False
159,0,0.0,0,0.0,1,0.0,0.2,0.2,0.0,0.0,Feb,3,2,3,3,Returning_Visitor,False,False
178,0,0.0,0,0.0,1,0.0,0.2,0.2,0.0,0.0,Feb,3,2,3,3,Returning_Visitor,False,False

In [75]:
# Drop the duplicates.
dataset = dataset.drop_duplicates()

In [ ]:
# Check for invalid values. Step recommended by ChatGPT
print((dataset[['BounceRates', 'ExitRates', 'SpecialDay']] < 0).sum())
print((dataset[['BounceRates', 'ExitRates', 'SpecialDay']] > 1).sum())
print((
    dataset[
        ['Administrative_Duration', 'Informational_Duration', 'ProductRelated_Duration']
    ]
    < 0
).sum())

BounceRates    0
ExitRates      0
SpecialDay     0
dtype: int64
BounceRates    0
ExitRates      0
SpecialDay     0
dtype: int64
Administrative_Duration    0
Informational_Duration     0
ProductRelated_Duration    0
dtype: int64

In [76]:
dataset.nunique().sort_values()

Revenue                       2
Weekend                       2
VisitorType                   3
SpecialDay                    6
OperatingSystems              8
Region                        9
Month                        10
Browser                      13
Informational                17
TrafficType                  20
Administrative               27
ProductRelated              311
Informational_Duration     1258
BounceRates                1872
PageValues                 2704
Administrative_Duration    3335
ExitRates                  4777
ProductRelated_Duration    9551
dtype: int64

In [77]:
# Converting Bools features into Binary features
dataset['Weekend'] = dataset['Weekend'].map({True: 1, False: 0})
dataset['Revenue'] = dataset['Revenue'].map({True: 1, False: 0})

In [78]:
# Convert categories into numerical features. Drop first used to reduce redundancy and
# correctly represent categorical values. Tree models may handle them as integers, but
# I chose to one hot encode as they are not ordered values.
# Categorical values listed here: https://archive.ics.uci.edu/dataset/468/online+shoppers+purchasing+intention+dataset
final_data_ohe = pd.get_dummies(
    dataset,
    columns=[
        'Month',
        'VisitorType',
        'TrafficType',
        'Region',
        'Browser',
        'OperatingSystems',
    ],
    drop_first=True,
)
final_data_ohe.info()

<class 'pandas.DataFrame'>
Index: 12205 entries, 0 to 12329
Data columns (total 69 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Administrative                 12205 non-null  int64
 1   Administrative_Duration        12205 non-null  float64
 2   Informational                  12205 non-null  int64
 3   Informational_Duration         12205 non-null  float64
 4   ProductRelated                 12205 non-null  int64
 5   ProductRelated_Duration        12205 non-null  float64
 6   BounceRates                    12205 non-null  float64
 7   ExitRates                      12205 non-null  float64
 8   PageValues                     12205 non-null  float64
 9   SpecialDay                     12205 non-null  float64
 10  Weekend                        12205 non-null  int64
 11  Revenue                        12205 non-null  int64
 12  Month_Dec                      12205 non-null  bool
 13  Month_Feb                      12205 non-null  bool
 14  Month_Jul                      12205 non-null  bool
 15  Month_June                     12205 non-null  bool
 16  Month_Mar                      12205 non-null  bool
 17  Month_May                      12205 non-null  bool
 18  Month_Nov                      12205 non-null  bool
 19  Month_Oct                      12205 non-null  bool
 20  Month_Sep                      12205 non-null  bool
 21  VisitorType_Other              12205 non-null  bool
 22  VisitorType_Returning_Visitor  12205 non-null  bool
 23  TrafficType_2                  12205 non-null  bool
 24  TrafficType_3                  12205 non-null  bool
 25  TrafficType_4                  12205 non-null  bool
 26  TrafficType_5                  12205 non-null  bool
 27  TrafficType_6                  12205 non-null  bool
 28  TrafficType_7                  12205 non-null  bool
 29  TrafficType_8                  12205 non-null  bool
 30  TrafficType_9                  12205 non-null  bool
 31  TrafficType_10                 12205 non-null  bool
 32  TrafficType_11                 12205 non-null  bool
 33  TrafficType_12                 12205 non-null  bool
 34  TrafficType_13                 12205 non-null  bool
 35  TrafficType_14                 12205 non-null  bool
 36  TrafficType_15                 12205 non-null  bool
 37  TrafficType_16                 12205 non-null  bool
 38  TrafficType_17                 12205 non-null  bool
 39  TrafficType_18                 12205 non-null  bool
 40  TrafficType_19                 12205 non-null  bool
 41  TrafficType_20                 12205 non-null  bool
 42  Region_2                       12205 non-null  bool
 43  Region_3                       12205 non-null  bool
 44  Region_4                       12205 non-null  bool
 45  Region_5                       12205 non-null  bool
 46  Region_6                       12205 non-null  bool
 47  Region_7                       12205 non-null  bool
 48  Region_8                       12205 non-null  bool
 49  Region_9                       12205 non-null  bool
 50  Browser_2                      12205 non-null  bool
 51  Browser_3                      12205 non-null  bool
 52  Browser_4                      12205 non-null  bool
 53  Browser_5                      12205 non-null  bool
 54  Browser_6                      12205 non-null  bool
 55  Browser_7                      12205 non-null  bool
 56  Browser_8                      12205 non-null  bool
 57  Browser_9                      12205 non-null  bool
 58  Browser_10                     12205 non-null  bool
 59  Browser_11                     12205 non-null  bool
 60  Browser_12                     12205 non-null  bool
 61  Browser_13                     12205 non-null  bool
 62  OperatingSystems_2             12205 non-null  bool
 63  OperatingSystems_3             12205 non-null  bool
 64  OperatingSystems_4             12205 non-null  bool
 65  OperatingSystems_5             12205 non-null  bool
 66  OperatingSystems_6             12205 non-null  bool
 67  OperatingSystems_7             12205 non-null  bool
 68  OperatingSystems_8             12205 non-null  bool
dtypes: bool(57), float64(7), int64(5)
memory usage: 1.9 MB

In [79]:
final_data_ohe.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,Browser_11,Browser_12,Browser_13,OperatingSystems_2,OperatingSystems_3,OperatingSystems_4,OperatingSystems_5,OperatingSystems_6,OperatingSystems_7,OperatingSystems_8
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,False,False,False,False,False,False,False,False,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,False,False,False,True,False,False,False,False,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,False,False,False,False,False,True,False,False,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,False,False,False,False,True,False,False,False,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,False,False,False,False,True,False,False,False,False,False